# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml .
COPY mcp_weather mcp_weather

# Install the MCP server
RUN pip install --upgrade pip && pip install .

# Use unbuffered output
ENV PYTHONUNBUFFERED=1

# Default command
CMD ["mcp-weather"]
